### ISSUE TITLE
Mapbox complains about "Invalid GL JSON"

### ISSUE THREAD

**Issue by Roadmaster** [federicomenaquintero/lamaperia#11]
I tried to follow the instructions on the README but when uploading the style, mapbox pops up a "Invalid GL JSON" message. Using commit bd42bf0dacf566446ae370db8eb34e5dc8b1e0fe.

**Comment by federicomenaquintero** [comment]
Yes, this is harder than I thought - see https://github.com/federicomenaquintero/lamaperia/issues/10

I've updated the configuration wizard to have default access parameters for Mapbox that should work out of the box.  Please update, delete your ~/.config/lamaperia and try again!

**Comment by elprincipe47** [comment]
Hello, I am trying to add a source to a layer in mapbox studio, 
i am getting invalid GL json
